name: qwer_english
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  appinio_swiper: ^2.1.0
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic.otf
    - family: NanumGothicBold
      fonts:
        - asset: assets/fonts/NanumGothicBold.otf
    - family: TommySoft
      fonts:
        - asset: assets/fonts/Tommy-Soft-Regular.otf
    - family: TommySoftBold
      fonts:
        - asset: assets/fonts/Tommy-Soft-Bold.otf
